version: "3.3"
services:
  vueapp:
    build: ./
    network_mode: "host"
    restart: "always"
    env_file: ".env"
    #  nginx:
    #    build: ./nginx
    #    network_mode: "host"
    #    volumes:
    #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    #    depends_on:
    #      - vueapp
#    ports:
#      - "8081:80"
#    ports:
#      - "${NGINX_PORT}:80"
